<a href="https://colab.research.google.com/github/argosmaia/Algorithms/blob/main/numpyex2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [ ]:
mt = np.array([12, 34, 26, 18, 10]) #matriz de uma linha
print(mt)
print(type(mt))

[12 34 26 18 10]
<class 'numpy.ndarray'>


In [ ]:
#cria um array com tipo específico
#cria o array com float de 64 bits
mtfloat = np.array([1, 2, 3], dtype=np.float64)
print(mtfloat)
print(type(mtfloat))
mtint = np.array([1, 2, 3], dtype=np.int32)
print(mtint)
print(type(mtint))

[1. 2. 3.]
<class 'numpy.ndarray'>
[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
#mudar o tipo do array
#transforma tipos de dados de array
mtnew = np.array([1.4, 3.6, -5.1, 9.42, 4.999999])
print(mtnew)
mtnewint = mtnew.astype(np.int32)
print(mtnewint)

[ 1.4       3.6      -5.1       9.42      4.999999]
[ 1  3 -5  9  4]


In [ ]:
#mudar o tipo do array
#transforma tipos de dados de array
mtint2 = np.array([1, 3, -5, 9, 4])
print(mtint2)
mtfloat = mtint2.astype(np.float64)
print(mtfloat)

[ 1  3 -5  9  4]
[ 1.  3. -5.  9.  4.]


In [ ]:
#matriz bidimensional
mtb = np.array([[3, 22, 12], [4, 7.5, 8], [32, 7, 10]])
print(mtb)

[[ 3.  22.  12. ]
 [ 4.   7.5  8. ]
 [32.   7.  10. ]]


In [ ]:
#cria arrays vazias tipificadas
vazio = np.empty([3, 2], dtype=np.int32)
print("MATRIZ COM CASAS VAZIAS\n")
print(vazio)
print("----------")
#cria uma matriz com valores zero
zeros = np.zeros([4, 3])
print("\nMATRIZ COM VALORES 0\n")
print(zeros)
print("----------")
#cria uma matriz com valores um
um = np.ones([5, 7])
print("\nMATRIZ COM VALORES 1\n")
print(um)
print("----------")
#cria uma matriz diagonal
diagonal = np.eye(5)
print("\nMATRIZ COM VALORES NA DIAGONAL\n")
print(diagonal)
print("----------")

MATRIZ COM CASAS VAZIAS

[[-1100012452  1071669463]
 [ -679990699  1072589362]
 [ 2063889932  1069708242]]
----------

MATRIZ COM VALORES 0

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
----------

MATRIZ COM VALORES 1

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
----------

MATRIZ COM VALORES NA DIAGONAL

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
----------


In [ ]:
#valores aleatórios entre 0 e 1
ale = np.random.random(5)
print("NUMEROS ALEATÓRIOS\n")
print(ale)
print("----------")
#valores aleatórios distr. normal contendo negativos
ale2 = np.random.randn(5)
print("\nNUMEROS ALEATÓRIOS CONTENDO NEGATIVOS\n")
print(ale2)
print("----------")
#valores aleatórios 3 x 4
ale3 = (10 * np.random.random((3, 4)))
print("\nNUMEROS ALEATÓRIOS EM UMA MATRIZ 3 x 4\n")
print(ale3)
print("----------")

NUMEROS ALEATÓRIOS

[0.49883024 0.54807839 0.90479873 0.84096538 0.52151196]
----------

NUMEROS ALEATÓRIOS CONTENDO NEGATIVOS

[-1.62768171 -0.1777138   0.60252258  0.18859261  0.78567839]
----------

NUMEROS ALEATÓRIOS EM UMA MATRIZ 3 x 4

[[2.69486449 9.56829759 4.5428173  7.5726378 ]
 [2.71360588 7.94449824 1.51213566 0.08443037]
 [0.44004813 0.40246723 8.28814954 2.5363332 ]]
----------


In [ ]:
#gerando numeros aleatórios com sementes
gnr = np.random.default_rng(1)
aleg = gnr.random(3)
print("MATRIZ COM NUMEROS ALEATÓRIOS\n")
print(aleg)
print("----------")
#gerar inteiros
alei = gnr.integers(10, size=(3, 4))
print("\nMATRIZ COM NUMEROS ALEATÓRIOS INTEIROS\n")
print(alei)
print("----------")

MATRIZ COM NUMEROS ALEATÓRIOS

[0.51182162 0.9504637  0.14415961]
----------

MATRIZ COM NUMEROS ALEATÓRIOS INTEIROS

[[8 9 2 3]
 [8 4 2 8]
 [2 4 6 5]]
----------


In [ ]:
#unique - remove repetições
j = np.array([11, 12, 12, 23, 23, 22, 24, 35, 35, 35])
j = np.unique(j)
print("MATRIZ COM NÚMEROS NÃO REPETIDOS\n")
print(j)
print("----------")


MATRIZ COM NUMEROS NÃO REPETIDOS

[11 12 22 23 24 35]
----------


In [ ]:
#cria a matriz bidimensional k
k = np.array([[17, 32, 35], [33, 73, 89], [22, 45, 56]])
print("MATRIZ 2D\n")
print(k)
print("----------")
#mostra um elemento especifíco
print("\nELEMENTOS ESPECIFÍCOS\n")
print(k[0][1])
print("----------")
#mostra o tamanho das dimensões
print("\nFORMAS:\n")
print(k.shape)
print("----------")

MATRIZ 2D

[[17 32 35]
 [33 73 89]
 [22 45 56]]
----------

ELEMENTOS ESPECIFÍCOS

32
----------

FORMAS:

(3, 3)
----------


In [ ]:

#Funções matemáticas
#mostra o maior valor da matriz k
print("MAIOR VALOR DE K:\n")
print(k.max())
print("----------")
#mostra o menor valor de k
print("\nMENOR VALOR DE K:\n")
print(k.min())
print("----------")
#soma dos elementos
print("\nSOMA DOS VALORES DE K:\n")
print(k.sum())
print("----------")
#media dos valores de k
print("\nMEDIA DOS VALORES DE K:\n")
print(k.mean())
print("----------")
#desvio padrão
print("\nDESVIÃO PADRÃO DE K:\n")
print(k.std())
print("----------")
#soma dos elementos

MAIOR VALOR DE K:

89
----------

MENOR VALOR DE K:

17
----------

SOMA DOS VALORES DE K:

402
----------

MEDIA DOS VALORES DE K:

44.666666666666664
----------

DESVIÃO PADRÃO DE K:

22.524061208701536
----------


In [ ]:
k1 = np.array([1, 4, 9, 16, 25])
k1 = np.sqrt(k1)
#imprime a raiz quadrada dos elementos da matriz
print("RAÍZ QUADRADA:\n")
print(k1)
print("----------")
#exponencial
print("\nEXPONENCIAL:\n")
k1 = np.exp(k1)
print(k1)
print("----------")

RAÍZ QUADRADA:

[1. 2. 3. 4. 5.]
----------

EXPONENCIAL:

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
----------


In [ ]:
#extração de elementos
m = np.array([1, 4, 9, 16, 25, 36])
#elemento da posição 2
print("ELEMENTO POSIÇÃO 2:\n")
print(m[1])
print("----------")
#mostra o elemento criado da posição 0, dois em dois
print("\nDOIS ELEMENTOS:\n")
print(m[0:2])
print("----------")
#mostra o array todo a partir do segundo elemento
print("\nMATRIZ:\n")
print(m[1:])
print("----------")
#mostra a partir da antepenúltima
print("\nANTEPENÚLTIMA:\n")
print(m[-3:])
print("----------")

ELEMENTO POSIÇÃO 2:

4
----------

DOIS ELEMENTOS:

[1 4]
----------

MATRIZ:

[ 4  9 16 25 36]
----------

ANTEPENÚLTIMA:

[16 25 36]
----------


In [5]:
#extração de linhas e colunas
l = np.array([[4, 6], [7, 1], [8, 5]])
print("MATRIZ GERADA:\n")
print(l)
print("----------")
#primeira linha, todas as colunas
linha_1 = l[0, :]
print("\nMATRIZ 1ª LINHA:\n")
print(linha_1)
print("----------")
#segunda linha, todas as colunas
linha_2 = l[1, :]
print("\nMATRIZ 2ª LINHA:\n")
print(linha_2)
print("----------")
#terceira linha, todas as colunas
linha_3 = l[2, :]
print("\nMATRIZ 3ª LINHA:\n")
print(linha_3)
print("----------")
#primeira coluna, todas as linhas
coluna_1 = l[:, 0]
print("\nMATRIZ 1ª LINHA:\n")
print(coluna_1)
print("----------")
#segunda coluna, todas as linhas
coluna_2 = l[:, 1]
print("\nMATRIZ 2ª LINHA:\n")
print(coluna_2)

MATRIZ GERADA:

[[4 6]
 [7 1]
 [8 5]]
----------

MATRIZ 1ª LINHA:

[4 6]
----------

MATRIZ 2ª LINHA:

[7 1]
----------

MATRIZ 3ª LINHA:

[8 5]
----------

MATRIZ 1ª LINHA:

[4 7 8]
----------

MATRIZ 2ª LINHA:

[6 1 5]


In [8]:
#adição e multiplicação
n = np.array([[1, 2], [3, 4]])
o = np.array([[1, 7], [8, 2]])
soma = n+o
print("MATRIZ SOMADA:\n")
print(soma)
print("----------")
mult = n*o
print("\nMATRIZ MULTIPLICADA:\n")
print(mult)
print("----------")
p = np.array([[1, 4], [9, 4], [3, 7]])
q = np.array([[3, 6]])
soma2 = p+q
print("\nMATRIZ SOMADA:\n")
print(soma2)
print("----------")

MATRIZ SOMADA:

[[ 2  9]
 [11  6]]
----------

MATRIZ MULTIPLICADA:

[[ 1 14]
 [24  8]]
----------

MATRIZ SOMADA:

[[ 4 10]
 [12 10]
 [ 6 13]]
----------


In [10]:
#transposição, rearranja um conjunto de 15 elementos de 0 à 14
#3 linhas, 5 colunas
f = np.arange(15).reshape(3, 5)
print("MATRIZ GERADA:\n")
print(f)
print("----------")
#matriz transposta
s = f.T
print("\nMATRIZ TRANSPOSTA:\n")
print(s)
print("----------")
#outro jeito de fazer
r = f.transpose(1, 0)
print("\nMATRIZ TRANSPOSTA DE OUTRO JEITO:\n")
print(r)
print("----------")

MATRIZ GERADA:

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
----------

MATRIZ TRANSPOSTA:

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
----------

MATRIZ TRANSPOSTA DE OUTRO JEITO:

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
----------


In [13]:
#expressões lógicas
#criando matriz com aleatórios pos e negs
v = np.random.randn(4, 4)
print("MATRIZ GERADA:\n")
print(v)
print("----------")
#matriz booleana
x = (v > 0)
print("\nMATRIZ BOOLEANA GERADA:\n")
print(x)
print("----------")
#matriz com valores -1 e 1 baseadas em x
z = np.where(x > 0, 1, -1)
print("\nMATRIZ 1 e -1 GERADA:\n")
print(z)
print("----------")

MATRIZ GERADA:

[[-0.03136371  0.92143816  2.03547677  1.37353003]
 [ 0.30393279  0.18583891 -0.51106334  0.52043172]
 [ 0.64888977 -0.31655056  1.63919269  1.12717301]
 [ 0.11667567 -1.75594693  1.16194929  0.69538275]]
----------

MATRIZ BOOLEANA GERADA:

[[False  True  True  True]
 [ True  True False  True]
 [ True False  True  True]
 [ True False  True  True]]
----------

MATRIZ 1 e -1 GERADA:

[[-1  1  1  1]
 [ 1  1 -1  1]
 [ 1 -1  1  1]
 [ 1 -1  1  1]]
----------
